package main

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

// InstallConfig is everything the wizard collected across its steps,
// handed to installService (implemented once per OS — see
// install_linux.go / install_windows.go / install_darwin.go).
type InstallConfig struct {
	Iface      string // step 2
	Mode       string // step 3: "strict" or "learning"
	DaemonPath string // resolved path to the sentryxd binary (step 4)
	CLIPath    string // resolved path to the sxctl binary (step 4)
	ConfDir    string
	DataDir    string
	Addr       string // control API listen address, e.g. ":9090"
	Token      string // generated bearer token
	Insecure   bool   // true only if token generation somehow failed — logged loudly, never silent
}

// InstallResult is what installService reports back to the wizard's Step
// 5 "done" screen.
type InstallResult struct {
	ServiceInstalled bool   `json:"service_installed"`
	ServiceManager   string `json:"service_manager"` // "systemd" | "Windows Service" | "launchd" | ""
	DashboardURL     string `json:"dashboard_url"`
	Detail           string `json:"detail"` // human-readable summary/next-step, shown on the done screen
}

// defaultConfDir / defaultDataDir mirror scripts/install.sh's Linux
// layout where possible, and fall back to OS-appropriate locations
// otherwise — see each install_<os>.go for exactly where these end up.
func defaultConfDir() string {
	switch runtime.GOOS {
	case "windows":
		base := os.Getenv("ProgramData")
		if base == "" {
			base = `C:\ProgramData`
		}
		return filepath.Join(base, "SENTRYX")
	case "darwin":
		return "/usr/local/etc/sentryx"
	default:
		return "/etc/sentryx"
	}
}

func defaultDataDir() string {
	switch runtime.GOOS {
	case "windows":
		base := os.Getenv("ProgramData")
		if base == "" {
			base = `C:\ProgramData`
		}
		return filepath.Join(base, "SENTRYX", "data")
	case "darwin":
		return "/usr/local/var/lib/sentryx"
	default:
		return "/var/lib/sentryx"
	}
}

// generateToken makes a fresh 32-byte bearer token, hex-encoded — same
// shape scripts/install.sh already generates via /dev/urandom, just done
// in Go so it works identically on every OS.
func generateToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generating token: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// minimalPolicyYAML is what the wizard writes on a fresh install — just
// enough for sentryxd to boot cleanly with an empty blocklist. An
// operator who wants Phase 17-25 features (SYN-cookie, knock, DNS, GeoIP)
// edits this afterward or runs `sxctl policy apply`; see
// internal/policy's Example for the annotated version `sxctl policy init`
// writes.
const minimalPolicyYAML = `# SENTRYX policy-as-code — generated by sentryx-setup.
# Edit this, then: sxctl policy apply policy.yaml
# See internal/policy's Example (sxctl policy init) for every available
# section (syn_cookie, knock, dns, geoip) with full documentation.
version: 1

block: []
`

// writePolicyAndEnv writes policy.yaml and the env file holding the
// generated bearer token into cfg.ConfDir, creating the directory tree if
// needed. Safe to call on a fresh install only — mirrors
// scripts/install.sh's "don't stomp an existing token" caution by
// refusing to overwrite an env file that's already there.
func writePolicyAndEnv(cfg InstallConfig) (envPath string, err error) {
	if err := os.MkdirAll(cfg.ConfDir, 0o755); err != nil {
		return "", fmt.Errorf("creating %s: %w", cfg.ConfDir, err)
	}
	if err := os.MkdirAll(cfg.DataDir, 0o755); err != nil {
		return "", fmt.Errorf("creating %s: %w", cfg.DataDir, err)
	}

	policyPath := filepath.Join(cfg.ConfDir, "policy.yaml")
	if _, err := os.Stat(policyPath); os.IsNotExist(err) {
		if err := os.WriteFile(policyPath, []byte(minimalPolicyYAML), 0o644); err != nil {
			return "", fmt.Errorf("writing %s: %w", policyPath, err)
		}
	}

	envPath = filepath.Join(cfg.ConfDir, "sentryx.env")
	if _, err := os.Stat(envPath); os.IsNotExist(err) {
		content := fmt.Sprintf("# Generated by sentryx-setup. Guards the control API — keep this file private.\nSENTRYX_TOKEN=%s\n", cfg.Token)
		if err := os.WriteFile(envPath, []byte(content), 0o600); err != nil {
			return "", fmt.Errorf("writing %s: %w", envPath, err)
		}
	}
	return envPath, nil
}

// dryRunFlag translates the wizard's strict/learning mode picker into the
// same -anomaly-dry-run flag main.go already exposes: "learning" mode
// detects and logs anomalies without ever auto-blocking, exactly like
// starting sentryxd with -anomaly-dry-run by hand.
func dryRunFlag(mode string) bool {
	return mode == "learning"
}
