#!/usr/bin/env bash
#
# SENTRYX installer — builds the daemon + CLI, installs them to
# /usr/local/bin, sets up /etc/sentryx and /var/lib/sentryx, generates an
# API token if one isn't already configured, and installs+enables the
# systemd service. Safe to re-run: it only ever overwrites files it manages.
#
# Usage:
#   sudo ./scripts/install.sh [-i eth0] [-o bpf/xdp_sentryx.o] [-t]
#
#   -t   Also generate a self-signed TLS certificate for the control API
#        (fine for a lab/demo; use a real cert from your CA/Let's Encrypt
#        in production instead — see internal/api's TLS notes).
#   -m   Also set up Phase 24 mTLS: generates a local CA, a server cert
#        signed by it (replacing the plain self-signed -t cert), and one
#        client cert (for `sxctl controller`/an operator workstation) also
#        signed by that CA. Implies -t.
#
# After it finishes:
#   systemctl status sentryxd
#   sxctl --token "$(grep SENTRYX_TOKEN /etc/sentryx/sentryx.env | cut -d= -f2)" list

set -euo pipefail

# This script is the Linux/systemd, build-from-source path (Phase 27.4).
# On Windows/macOS there's no XDP data plane to build and no systemd to
# hand off to — use the Phase 28 GUI installer instead (cmd/sentryx-setup,
# or a downloaded sentryx-setup-<os>-<arch> release asset): it downloads
# the matching pre-built sentryxd/sxctl for your OS/arch and installs them
# as a native Windows Service / launchd agent, no terminal required.
OS_NAME="$(uname -s)"
if [[ "$OS_NAME" != "Linux" ]]; then
  echo "this script installs the systemd service and only runs on Linux (detected: $OS_NAME)." >&2
  echo "on Windows/macOS, run the Phase 28 GUI installer (sentryx-setup) instead — see README.md." >&2
  exit 1
fi

IFACE="eth0"
OBJ_PATH=""
PREFIX="/usr/local/bin"
CONF_DIR="/etc/sentryx"
DATA_DIR="/var/lib/sentryx"
SYSTEMD_DIR="/etc/systemd/system"
GEN_TLS=0
GEN_MTLS=0

while getopts "i:o:tmh" opt; do
  case "$opt" in
    i) IFACE="$OPTARG" ;;
    o) OBJ_PATH="$OPTARG" ;;
    t) GEN_TLS=1 ;;
    m) GEN_TLS=1; GEN_MTLS=1 ;;
    h)
      echo "Usage: sudo ./scripts/install.sh [-i iface] [-o path/to/xdp_sentryx.o] [-t] [-m]"
      exit 0
      ;;
    *) exit 1 ;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  echo "this installer needs root (it writes to /etc, /var/lib, /usr/local/bin, and systemd) — re-run with sudo" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "==> building SENTRYX (daemon + CLI + XDP object)"
make all

if [[ -z "$OBJ_PATH" ]]; then
  OBJ_PATH="$CONF_DIR/xdp_sentryx.o"
fi

echo "==> installing binaries to $PREFIX"
install -m 0755 bin/sentryxd "$PREFIX/sentryxd"
install -m 0755 bin/sxctl "$PREFIX/sxctl"

echo "==> setting up $CONF_DIR and $DATA_DIR"
mkdir -p "$CONF_DIR" "$DATA_DIR"
install -m 0644 bpf/xdp_sentryx.o "$CONF_DIR/xdp_sentryx.o"

if [[ ! -f "$CONF_DIR/policy.yaml" ]]; then
  "$PREFIX/sxctl" policy init --out "$CONF_DIR/policy.yaml"
fi

ENV_FILE="$CONF_DIR/sentryx.env"
if [[ ! -f "$ENV_FILE" ]]; then
  TOKEN="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/install.sh on $(date -u +%FT%TZ).
# This token guards the control API — keep this file root-readable only.
SENTRYX_TOKEN=$TOKEN
EOF
  chmod 0600 "$ENV_FILE"
  echo "==> generated a fresh API token in $ENV_FILE (chmod 600)"
else
  echo "==> $ENV_FILE already exists, leaving it untouched"
fi

TLS_ARGS=""
if [[ "$GEN_TLS" -eq 1 ]]; then
  if [[ "$GEN_MTLS" -eq 1 ]]; then
    if [[ ! -f "$CONF_DIR/ca.crt" ]]; then
      echo "==> generating a local CA + mTLS server/client certs in $CONF_DIR (Phase 24)"
      openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
        -keyout "$CONF_DIR/ca.key" -out "$CONF_DIR/ca.crt" \
        -subj "/CN=sentryx-fleet-ca" >/dev/null 2>&1
      chmod 0600 "$CONF_DIR/ca.key"

      # Server cert, signed by the CA above, replacing the plain
      # self-signed one -t alone would generate.
      openssl req -nodes -newkey rsa:2048 \
        -keyout "$CONF_DIR/tls.key" -out "$CONF_DIR/tls.csr" \
        -subj "/CN=sentryx" >/dev/null 2>&1
      openssl x509 -req -in "$CONF_DIR/tls.csr" -CA "$CONF_DIR/ca.crt" -CAkey "$CONF_DIR/ca.key" \
        -CAcreateserial -days 825 -out "$CONF_DIR/tls.crt" >/dev/null 2>&1
      rm -f "$CONF_DIR/tls.csr"
      chmod 0600 "$CONF_DIR/tls.key"

      # One client cert for the controller/an operator workstation. Copy
      # $CONF_DIR/client.{crt,key} + ca.crt off-box to wherever `sxctl
      # controller` runs from — see --client-cert/--client-key/--ca.
      openssl req -nodes -newkey rsa:2048 \
        -keyout "$CONF_DIR/client.key" -out "$CONF_DIR/client.csr" \
        -subj "/CN=sentryx-controller" >/dev/null 2>&1
      openssl x509 -req -in "$CONF_DIR/client.csr" -CA "$CONF_DIR/ca.crt" -CAkey "$CONF_DIR/ca.key" \
        -CAcreateserial -days 825 -out "$CONF_DIR/client.crt" >/dev/null 2>&1
      rm -f "$CONF_DIR/client.csr"
      chmod 0600 "$CONF_DIR/client.key"
    else
      echo "==> $CONF_DIR/ca.crt already exists, leaving CA + certs untouched"
    fi
    TLS_ARGS="-tls-cert $CONF_DIR/tls.crt -tls-key $CONF_DIR/tls.key -mtls-ca $CONF_DIR/ca.crt"
  elif [[ ! -f "$CONF_DIR/tls.crt" ]]; then
    echo "==> generating a self-signed TLS certificate in $CONF_DIR"
    openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
      -keyout "$CONF_DIR/tls.key" -out "$CONF_DIR/tls.crt" \
      -subj "/CN=sentryx" >/dev/null 2>&1
    chmod 0600 "$CONF_DIR/tls.key"
    TLS_ARGS="-tls-cert $CONF_DIR/tls.crt -tls-key $CONF_DIR/tls.key"
  else
    echo "==> $CONF_DIR/tls.crt already exists, leaving it untouched"
    TLS_ARGS="-tls-cert $CONF_DIR/tls.crt -tls-key $CONF_DIR/tls.key"
  fi
fi

echo "==> installing systemd unit"
sed \
  -e "s|__IFACE__|$IFACE|g" \
  -e "s|__OBJ_PATH__|$OBJ_PATH|g" \
  -e "s|__DATA_DIR__|$DATA_DIR|g" \
  -e "s|__CONF_DIR__|$CONF_DIR|g" \
  -e "s|__ENV_FILE__|$ENV_FILE|g" \
  -e "s|__TLS_ARGS__|$TLS_ARGS|g" \
  "$REPO_ROOT/scripts/sentryxd.service" > "$SYSTEMD_DIR/sentryxd.service"

systemctl daemon-reload
systemctl enable sentryxd
systemctl restart sentryxd

echo
echo "==> running sxctl doctor (post-install sanity check)"
"$PREFIX/sxctl" doctor --iface "$IFACE" || echo "    (doctor reported warnings/failures above — sentryxd may still be starting up)"

echo
echo "==> done. sentryxd is running on interface $IFACE."
echo "    systemctl status sentryxd"
echo "    journalctl -u sentryxd -f"
echo "    sxctl --token \"\$(grep SENTRYX_TOKEN $ENV_FILE | cut -d= -f2)\" list"
if [[ "$GEN_MTLS" -eq 1 ]]; then
  echo
  echo "==> mTLS is enabled. Copy $CONF_DIR/{ca.crt,client.crt,client.key} to wherever"
  echo "    sxctl controller runs from, then pass --ca/--client-cert/--client-key."
fi
